### ISSUE TITLE
optimizer fails to find .js file right under its nose

### ISSUE THREAD

**Issue by ORESoftware** [requirejs/r.js#951]
I have this error:

```
Tracing dependencies for: /home/oleg/WebstormProjects/oresoftware/hr4r2/public/optimized/bundles/home-view.js
Error: ENOENT: no such file or directory, open '/home/oleg/WebstormProjects/oresoftware/hr4r2/public/js/data-stores/redux-store'  <<<<<
In module tree:
    /home/oleg/WebstormProjects/oresoftware/hr4r2/public/js/views/home/home.js

Error: Error: ENOENT: no such file or directory, open '/home/oleg/WebstormProjects/oresoftware/hr4r2/public/js/data-stores/redux-store'
In module tree:
    /home/oleg/WebstormProjects/oresoftware/hr4r2/public/js/views/home/home.js

    at Object.fs.openSync (fs.js:557:18)

    at /home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:25865:19
    at /home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:3056:39
    at /home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:2996:25
    at Function.prim.nextTick (/home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:25616:9)
    at Object.errback (/home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:2995:26)
    at Object.callback (/home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:2981:23)
    at Object.then (/home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:3035:23)
    at build (/home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:25822:12)
    at runBuild (/home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:27831:17)
    at Object.execCb (/home/oleg/WebstormProjects/oresoftware/hr4r2/node_modules/requirejs/bin/r.js:1943:33)
chmod: cannot access 'public/optimized': No such file or directory

```

Here the AMD module in question (was transpiled by TypeScript):

```

var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};


define(["require", "exports", "react", "../../data-stores/redux-store", "uuid"], function (require, exports, React, store, uuid) {
    "use strict";
    var asyncActionCreator = function () {
        return function (dispatch) {
            fetch('https://www.reddit.com/subreddits/search.json?q=reactjs', {
                method: 'get',
            }).then(function (response) {
                console.log('response => ', response);
                response.json().then(function (json) {
                    console.log('json => ', json);
                    dispatch({
                        type: 'GET_REACTJS_REDDIT',
                        result: json.data.children.map(function (c) {
                            return {
                                title: c.data.title,
                                description: c.data.public_description,
                                image: c.data.header_img
                            };
                        })
                    });
                });
            }).catch(function (err) {
                console.error(err.stack || err);
            });
        };
    };
    var i = 0;
    return (function (_super) {
        __extends(Home, _super);
        function Home(props) {
            var _this = _super.call(this, props) || this;
            _this.onClickRetrieve = _this.onClickRetrieve.bind(_this);
            _this.state = {
                clicked: false,
                items: []
            };
            return _this;
        }
        Home.prototype.componentDidMount = function () {
             /// truncated
            });
        
     
        return Home;
    }(React.Component));
});

```

r.js is tracing this module for deps and sees this:

` "../../data-stores/redux-store"`

this came from standard ES6 import syntax. r.js should be able to assume this path points to a .js file in the same exact path. But we get this error:

`Error: ENOENT: no such file or directory, open '/home/oleg/WebstormProjects/oresoftware/hr4r2/public/js/data-stores/redux-store' `

but quite literally the following file exists:
'/home/oleg/WebstormProjects/oresoftware/hr4r2/public/js/data-stores/redux-store.js' 

what to do?

**Comment by ORESoftware** [comment]
this is happening for multiple files - these are just regular AMD modules nothing crazy

**Comment by ORESoftware** [comment]
here's one debugging clue - if I go into the transpiled file and change:

define(["require", "exports", "react", "../../data-stores/redux-store", "uuid"], function (require, exports, React, store, uuid) {

to

define(["require", "exports", "react", "../../data-stores/redux-store.js", "uuid"], function (require, exports, React, store, uuid) {


it will work, so, my only thinking is that if you get an ENOENT, tack on a .js to the file path and try one more time

**Comment by azizhk** [comment]
See the extension of the redux-store file, is it `.js.js`

**Comment by ORESoftware** [comment]
no I don't think so, these files are just `.js`, but I will double check

**Comment by ORESoftware** [comment]
yeah just regular old .js files :)

![screenshot from 2017-01-31 00-39-50](https://cloud.githubusercontent.com/assets/11139560/22457714/d1351008-e74d-11e6-96e3-38e9b69d766a.png)

**Comment by Arun789788** [comment]
401: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission &#39;storage.objects.get&#39; denied on resource (or it may not exist).
